//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingOfArrivalApp.Classes
{
    using System.Collections.Generic;

    public partial class Counterparties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Counterparties()
        {
            this.InvoicesOnArrival = new HashSet<InvoicesOnArrival>();
        }
    
        public int idCounterparty { get; set; }
        public string Name { get; set; }
        public string INN { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicesOnArrival> InvoicesOnArrival { get; set; }

        public static Counterparties New(Counterparties c)
        {
            return new Counterparties() { Name = c.Name, INN = c.INN, Address = c.Address };
        }
        public static void UndoСhanges(Counterparties current, Counterparties old)
        {
            if (current == null || old == null) return;
            current.Name = old.Name;
            current.INN = old.INN;
            current.Address = old.Address;
        }
    }
}
